# Generated by Django 4.2.13 on 2024-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentDetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_message', models.TextField()),
                ('intent_response', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='intentdetectionhistory',
            constraint=models.UniqueConstraint(fields=('input_message', 'goal'), name='unique_input_message_goal'),
        ),
    ]
